import { Link } from 'react-router-dom';
import { Clock, Eye, ArrowUpRight } from 'lucide-react';
import { DbArticle,timeAgo } from '@/hooks/use-articles';
import { motion } from 'framer-motion';
const formatViews=(n:number)=>n>=1000?`${(n/1000).toFixed(1)}k`:`${n}`;
interface Props{article:DbArticle;variant?:'default'|'featured'|'compact'|'horizontal'}
const Meta=({article,light=false}:{article:DbArticle;light?:boolean})=><div className={`flex flex-wrap items-center gap-2 font-mono text-[9px] uppercase ${light?'text-background/70':'text-muted-foreground'}`}><span>{article.author_name}</span><span>•</span><span>{timeAgo(article.published_at)}</span><span>•</span><span className="flex items-center gap-1"><Eye className="w-3 h-3"/>{formatViews(article.views||0)}</span></div>;
const ArticleCard=({article,variant='default'}:Props)=>{
 if(variant==='compact')return <Link to={`/article/${article.slug}`} className="group grid grid-cols-[2.25rem_1fr] gap-3 py-4 border-b border-foreground/15"><span className="font-display text-3xl text-primary/25 leading-none group-hover:text-primary transition-colors">›</span><div><h3 className="font-display text-sm leading-tight group-hover:text-primary transition-colors line-clamp-2">{article.title}</h3><div className="mt-2"><Meta article={article}/></div></div></Link>;
 if(variant==='horizontal')return <motion.article initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><Link to={`/article/${article.slug}`} className="group grid grid-cols-[7.5rem_1fr] md:grid-cols-[13rem_1fr] gap-4 md:gap-6 py-5 border-t border-foreground/20"><div className="overflow-hidden aspect-[4/3]"><img src={article.cover_image||'/placeholder.svg'} alt={article.title} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" loading="lazy"/></div><div className="flex flex-col justify-between py-1"><div><span className="font-mono text-[9px] font-bold uppercase text-primary tracking-widest">{article.category_name||'News'}</span><h3 className="font-display text-base md:text-xl leading-tight mt-1 group-hover:text-primary transition-colors line-clamp-2">{article.title}</h3><p className="hidden md:block text-sm text-muted-foreground mt-2 line-clamp-2">{article.excerpt}</p></div><Meta article={article}/></div></Link></motion.article>;
 if(variant==='featured')return <motion.article initial={{opacity:0}} animate={{opacity:1}} className="group"><Link to={`/article/${article.slug}`} className="block"><div className="relative overflow-hidden aspect-[4/5] md:aspect-[4/5] lg:aspect-[5/6] image-reveal"><img src={article.cover_image||'/placeholder.svg'} alt={article.title} className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105"/><span className="absolute top-4 left-4 bg-foreground text-background px-3 py-1 font-mono text-[9px] uppercase tracking-widest">Lead story</span></div><div className="pt-5"><span className="font-mono text-[10px] font-bold uppercase text-primary tracking-widest">{article.category_name||'Top story'}</span><h2 className="font-display text-2xl md:text-4xl leading-[1.03] mt-2 group-hover:text-primary transition-colors">{article.title}</h2><p className="text-base text-muted-foreground leading-relaxed mt-3 line-clamp-2">{article.excerpt}</p><div className="mt-4"><Meta article={article}/></div></div></Link></motion.article>;
 return <motion.article initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="group border-t-2 border-foreground pt-3"><Link to={`/article/${article.slug}`}><div className="overflow-hidden aspect-[4/3]"><img src={article.cover_image||'/placeholder.svg'} alt={article.title} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" loading="lazy"/></div><div className="pt-4"><div className="flex justify-between gap-3"><span className="font-mono text-[9px] font-bold uppercase text-primary tracking-widest">{article.category_name||'News'}</span><ArrowUpRight className="w-4 h-4 group-hover:text-primary"/></div><h3 className="font-display text-lg leading-tight mt-2 group-hover:text-primary transition-colors line-clamp-2">{article.title}</h3><p className="text-sm text-muted-foreground mt-2 line-clamp-2">{article.excerpt}</p><div className="mt-3"><Meta article={article}/></div></div></Link></motion.article>;
};
export default ArticleCard;
